#!/bin/bash

if [ -L "/var/jb" ]; then
    launchctl unload /var/jb/Library/LaunchDaemons/com.julioverne.screendumpd.plist
else
    launchctl unload /Library/LaunchDaemons/com.julioverne.screendumpd.plist
fi

exit 0;